__author__'"Vijay Lakhujani"

def reverse_complement(seq):
    '''
        This function takes the strech of DNA from 'get_sequence'
        function and returs reverse complimented stretc
    '''

    reverse_seq_list=seq[::-1]
    reverse_complemented=[]
    seq_dict = {'T':'A','A':'T','G':'C','C':'G'}
    reverse_complemented="".join(map(lambda x: seq_dict[x] , reverse_seq_list))
    return reverse_complemented

DNA_stretch='AGGGGGCTTTGTATAGCGCTGCATTTCTTGCAACTGGTCGGTAATCACTTAGGCTGAGCACCGCGGGTGGTGGGTACGAAGCTCGGGTCCTGGTAAGGAGTAAGTAAGGCTCATCGATATTGTGACTATGGCAGAATTACGGTAGATTTATTAAGGTAATCAATAGGTATTGGCAAGGGACGTGAGGAGCCCTGGAGTGAACACTGCTCGGCGTTATGTAAGGAATGAAGCTTGGGATTAAATCAACATATCATGCGGTTTAGTATAGCGCTCCCTCGCCGAGGAATAAGCACGAACCAAGGGTATTCACATATTTTGTAGGGTTTATTCCCCCCACGCCCGTGGTCCTTGTTTCTGTACAAACCGGGAGGTTGATCGACACCAGACCGCTGTTTGTGTCAGTTGTTTTAGGGCCCTAGAGCCTGTATCGTAACGTTGCGGAAAAGGAGGACGAGGCGTAGTCCCTGGTATGTCCCACAGTTCTCATGCAACTATGACGAGTTTAGCTGGTTACGGTAATGTATATCACAAGAATGCGAGGTGCGTGGGGGTTCAACCCCCCTTGAGACAGGCTGGTCCGCACGCTAGAACTCCTATAGGGTTCATGCCGGTATGTCCCTGTCCTGTAGTTATCCACAGATATTTCGAATCGAGACCTAGTCTGTGCCCCTCAGACGCTGTCGAGGCTACGTCACGCCCACACCTAAAAATTCAGATGCGCACCACTAACTTCATACAACCCAGCCATGGACCAACCACTTGTGTTTACAGCTTGCTACCCCCGAGAAGCTAAAGACGCTCTCGCAGCTTGTACGTGCTGCGGGCGTTGCATATGGGCGCACCTCTGACTATTGAAGTTCCTTGTA'

reverse_complemented = reverse_complement(DNA_stretch)

print 'reverse_complemented: ' ,"".join(reverse_complemented ), '\n\n'
